import numpy as np
import sympy as sp

import warnings

try:
    import brian2
    from brian2.units import (
        ms, 
        mV,
        nS, uS, 
        pA, nA, uA,
        pF, nF, uF, 
        um2, cm2, 
        um, cm,
        Mohm
    )
    _BRIAN2_AVAILABLE = True
except ImportError:
    _BRIAN2_AVAILABLE = False
    warnings.warn(
        "brian2 is not installed. Brian2CompartmentTree requires brian2 "
        "to export models.",
        ImportWarning,
    )


from typing import Dict, List, Optional, Tuple


from ...trees.compartmenttree import CompartmentTree, CompartmentNode
from ...factorydefaults import DefaultPhysiology


CFG = DefaultPhysiology()


def _piecewise_to_masked_expr(expr):
    """
    Rewrite SymPy Piecewise into arithmetic masking using int(condition).

    Brian2 equation strings do not accept Python ternary syntax generated by
    ``sp.pycode`` for Piecewise. This conversion keeps expressions equivalent
    while using syntax Brian2 accepts.
    """

    def _convert(pw):
        if not isinstance(pw, sp.Piecewise):
            return pw

        default_expr = None
        for branch_expr, branch_cond in pw.args:
            if branch_cond == True:
                default_expr = branch_expr
                break
        if default_expr is None:
            default_expr = sp.Integer(0)

        acc = default_expr
        for branch_expr, branch_cond in reversed(pw.args):
            if branch_cond == True:
                continue
            mask = sp.Function('bint')(branch_cond)
            acc = mask * branch_expr + (sp.Integer(1) - mask) * acc
        return acc

    return expr.replace(lambda e: isinstance(e, sp.Piecewise), _convert)


def _sympy_to_brian2_str(expr):
    """
    Convert a sympy expression to a Python/Brian2-parseable string.

    We use ``sp.pycode`` with ``fully_qualified_modules=False`` so that
    functions like ``exp`` are emitted without a ``math.`` prefix. Brian2's
    namespace provides the required ufuncs.
    """
    expr = _piecewise_to_masked_expr(expr)
    return sp.pycode(
        expr,
        fully_qualified_modules=False,
        user_functions={"bint": "int"},
    )


def ion_channel_brian2_eqs(chan, chan_name):
    """
    Generate Brian2 equation fragments for a NEAT IonChannel instance.

    NEAT's IonChannel stores:
      - chan.p_open         : sympy expression in state-variable symbols
      - chan.varinf[svar]   : sympy expression for x_inf(v)   [dimensionless]
      - chan.tauinf[svar]   : sympy expression for tau_x(v)   [ms, after q10]
      - chan.ordered_statevars : list of sympy symbols, e.g. [h, m]
      - chan.conc           : SPDict {ion_symbol: default_float}
      - chan._substitute_defaults(expr) : substitutes temp (and e) defaults

    Brian2 uses volts for v, while NEAT expressions are in mV.  We substitute
    the sympy symbol 'v' with the expression 'v/mV' before printing, so that
    the emitted string contains e.g.  'exp(0.1 * (v/mV + 38))' which is
    dimensionally correct when v carries Brian2 volt units.

    Parameters
    ----------
    chan : IonChannel
    chan_name : str
        Used as suffix in all variable/parameter names, e.g. 'Na_Ta'.

    Returns
    -------
    channel_eqs : str
        Channel-specific state equations and current-density definition.
    current_var : str
        Name of the current density variable contributed by the channel.
    param_decls : list[str]
        Brian2 parameter declaration lines for gbar and e_rev.
    """
    sp_v = chan.sp_v          # sympy Symbol('v'), NEAT voltage in mV

    # Substitution: v [mV]  ->  v/mV  so Brian2 evaluates correctly in volts
    sp_v_scaled = sp.Symbol('v') / sp.Symbol('mV')
    conc_subs = {
        c_sym: sp.Symbol(f'c_{str(c_sym)}')
        for c_sym in chan.conc
    }

    gating_lines = []

    for svar in chan.ordered_statevars:
        svar_str  = str(svar)
        brian_var = f'{svar_str}_{chan_name}'   # e.g. 'm_Na_Ta'

        # -- varinf -------------------------------------------------------
        varinf = chan._substitute_defaults(chan.varinf[svar])
        for c_sym, c_var in conc_subs.items():
            varinf = varinf.subs(c_sym, c_var)
        varinf = varinf.subs(sp_v, sp_v_scaled)
        varinf_str = _sympy_to_brian2_str(varinf)

        # -- tauinf -------------------------------------------------------
        # tauinf is in ms (already divided by q10 in IonChannel.__init__)
        # Brian2 ODE time unit is seconds, so we emit  (tauinf_expr) * ms
        tauinf = chan._substitute_defaults(chan.tauinf[svar])
        for c_sym, c_var in conc_subs.items():
            tauinf = tauinf.subs(c_sym, c_var)
        tauinf = tauinf.subs(sp_v, sp_v_scaled)
        tauinf_str = _sympy_to_brian2_str(tauinf)

        # -- ODE ----------------------------------------------------------
        gating_lines.append(
            f'd{brian_var}/dt = ({varinf_str} - {brian_var}) '
            f'/ (({tauinf_str}) * ms) : 1'
        )

    # -- Im contribution --------------------------------------------------
    # Rewrite p_open substituting each state variable symbol with the
    # suffixed Brian2 name, e.g. m -> m_Na_Ta, h -> h_Na_Ta
    p_open = chan.p_open
    for svar in chan.ordered_statevars:
        p_open = p_open.subs(svar, sp.Symbol(f'{str(svar)}_{chan_name}'))
    for c_sym, c_var in conc_subs.items():
        p_open = p_open.subs(c_sym, c_var)
    p_open = p_open.subs(sp_v, sp_v_scaled)
    p_open_str = _sympy_to_brian2_str(p_open)

    current_var = f'i_{chan_name}'
    gating_lines.append(
        f'{current_var} = gbar_{chan_name} * ({p_open_str}) '
        f'* (e_{chan_name} - v) : amp/metre**2'
    )

    # -- Parameter declarations -------------------------------------------
    param_decls = [
        f'gbar_{chan_name} : siemens/metre**2',
        f'e_{chan_name}    : volt',
    ]

    return '\n'.join(gating_lines), current_var, param_decls


class Brian2CompartmentNode(CompartmentNode):
    def __init__(self, index, **kwargs):
        super().__init__(index, **kwargs)
        self.fake_length = np.nan
        self.fake_radius = np.nan

    @property
    def fake_surface(self):
        # cylindrical section surface area (not including end caps), in cm^2
        return 2 * np.pi * self.fake_radius * self.fake_length


class Brian2CompartmentTree(CompartmentTree):
    """
    Converts a fitted NEAT ``CompartmentTree`` into a Brian2 ``SpatialNeuron``
    integrated with the Hines implicit solver.

    Parameters
    ----------
    ctree : neat.CompartmentTree
        A compartment tree with fitted parameters.
    r_fake : float, optional
        Fake cylinder radius [m] (default 1 µm = 1e-6 m).
    c_m : float, optional
        Specific membrane capacitance [F/m^2] (default 0.01 = 1 µF/cm^2).
    Ra : float or None, optional
        Global axial resistivity [ohm·m].  If None (default), derived as
        the median of the values that reproduce every coupling conductance
        exactly at d = 2*r_fake, minimising per-section diameter corrections.
    """

    def __init__(self, arg=None, channel_storage: Optional[Dict[str, "IonChannel"]] = None):
        super().__init__(arg)
        self._channel_storage = channel_storage or getattr(self, "channel_storage", {})

        # auxiliary constants for fake geometry calculation
        self.fake_c_m = 1.0 # [uF / cm^2]
        self.fake_r_a = 100.0 * 1e-6 # [MOhm * cm]

    def create_corresponding_node(self, index, **kwargs):
        """
        Creates a node with the given index corresponding to the tree class.

        Parameters
        ----------
        node_index: int
            index of the new node
        **kwargs
            Parameters of the parent class node initialization function
        """
        return Brian2CompartmentNode(index, **kwargs)

    def _build_morphology(self):
        lengths, radii = self.compute_fake_geometry(
            fake_c_m=self.fake_c_m,
            fake_r_a=self.fake_r_a,
            method='brian2',
        )

        for ii, node in enumerate(self):
            node.fake_length = lengths[ii]
            node.fake_radius = radii[ii]

        bmorph = self._build_brian_morphology()
        self.compartment_index = {
            node.index: int(np.atleast_1d(self.morph_map[node.index].indices[:])[0])
            for node in self
        }

        return bmorph

    def get_compartment_index(self, node_or_index):
        if hasattr(node_or_index, "index"):
            node_index = node_or_index.index
        else:
            node_index = int(node_or_index)
        return self.compartment_index[node_index]

    def _set_node_state(self, bneuron, var_name, node, value, use_units=True):
        bneuron.state(var_name, use_units=use_units)[self.get_compartment_index(node)] = value

    def _set_all_state(self, bneuron, var_name, value, use_units=True):
        bneuron.state(var_name, use_units=use_units)[:] = value
    
    def morpho_access_string(self, node, prefix=''):
        """
        Return the string to access the corresponding node's 
        parameters in the Brian2 model.

        Parameters
        ----------
        node : CompartmentNode
            The node for which to generate the access string.
        prefix : str, optional
            Prefix for the access string, e.g. the variable name of the
            Brian2 model instance (default '').

        Returns
        -------
        access_str : str
            A string that can be used to access the node's parameters in the
            Brian2 model, e.g. 'bneuron.c3.c5' for a node with path [root, c3, c5].
        """
        path = self.path_to_root(node)[::-1] # from root to node
        access_str = prefix
        for n in path[1:]: # skip root
            access_str += f'.c{n.index}'
        return access_str

    def _build_brian_morphology(self, node=None, bmorph=None):
        if node is None:
            node   = self.root
            bmorph = brian2.Cylinder(
                diameter=2.0 * node.fake_radius * cm,
                length=node.fake_length * cm,
                n=1
            )
            self.morph_map = {node.index: bmorph}
        
        for cnode in node.child_nodes:
            section = brian2.Cylinder(
                diameter=2.0 * cnode.fake_radius * cm,
                length=cnode.fake_length * cm,
                n=1,
            )
            # Direct attribute assignment on the parent object — this is what
            # actually wires the section into the morphology tree
            setattr(self.morph_map[node.index], f'c{cnode.index}', section)
            # Read back from parent after registration (not the pre-assignment object)
            self.morph_map[cnode.index] = getattr(
                self.morph_map[node.index], f'c{cnode.index}'
            )
            self._build_brian_morphology(node=cnode, bmorph=bmorph)

        return bmorph

    def _concentration_ions(self):
        ions = {ion for node in self for ion in node.concmechs}
        for channel in self._channel_storage.values():
            ions.update(str(ion) for ion in channel.conc)
        return sorted(ions)

    def _default_concentration(self, ion):
        for channel in self._channel_storage.values():
            for c_sym, c_val in channel.conc.items():
                if str(c_sym) == ion:
                    return c_val
        return CFG.conc[ion]

    def _initial_concentration(self, node, ion):
        if ion in node.conc_eqs:
            return node.conc_eqs[ion]
        if ion in node.concmechs:
            return node.concmechs[ion].inf
        return self._default_concentration(ion)

    def _concentration_equations(self, ion_current_terms):
        ions = self._concentration_ions()
        if len(ions) == 0:
            return [], []

        conc_lines = []
        param_decls = ['A_comp : metre**2']

        for ion in ions:
            current_terms = ion_current_terms.get(ion, [])
            if len(current_terms) > 0:
                current_expr = ' + '.join(current_terms)
                conc_lines.append(f'i_{ion} = A_comp * ({current_expr}) : amp')
            else:
                conc_lines.append(f'i_{ion} = 0 * amp : amp')

            conc_lines.append(
                f'dc_{ion}/dt = (inf_{ion} - c_{ion}) / tau_{ion} '
                f'+ gamma_{ion} * (i_{ion} / nA) / ms : 1'
            )
            param_decls.extend(
                [
                    f'gamma_{ion} : 1',
                    f'tau_{ion}   : second',
                    f'inf_{ion}   : 1',
                ]
            )

        return conc_lines, param_decls

    def _build_equations(self):
        """
        Assemble the full SpatialNeuron equation string.

        Contributions:
          - leak:    gL * (eL - v)
          - channel: gbar_X * p_open_X(state_vars) * (e_X - v)

        Gating ODEs are generated once per channel type from sympy.
        All channel-specific parameters are declared as (shared) so that
        they can be set per-compartment after construction.
        """
        im_terms      = ['gL * (eL - v)']
        gating_blocks = []
        param_decls   = [
            'gL    : siemens/metre**2',
            'eL    : volt',
            'I_ext : amp (point current)',
        ]
        ion_current_terms = {ion: [] for ion in self._concentration_ions()}
        
        # ion channel contributions
        for cname, channel in self._channel_storage.items():
            gating_eqs, current_var, pdecls = ion_channel_brian2_eqs(channel, cname)
            gating_blocks.append(gating_eqs)
            im_terms.append(current_var)
            param_decls.extend(pdecls)

            ion = getattr(channel, "ion", None)
            if ion is not None:
                ion = str(ion)
                if ion in ion_current_terms:
                    ion_current_terms[ion].append(current_var)

        conc_eqs, conc_params = self._concentration_equations(ion_current_terms)
        param_decls.extend(conc_params)
        
        # synapse contributions
        syn_odes, syn_params = self._synapse_equations()
        param_decls.extend(syn_params)

        im_line = 'Im = ' + ' + '.join(im_terms) + ' : amp/metre**2'

        return '\n'.join(gating_blocks + conc_eqs + syn_odes + [im_line] + param_decls)

    def _set_parameters(self, bneuron):
        conc_ions = self._concentration_ions()
        for syn_name, syn in getattr(self, '_synapses', {}).items():
            self._set_all_state(
                bneuron, f"e_{syn_name}", syn["e_rev_mV"] * mV, use_units=True
            )

        for node in self:
            for cname, (g, e) in node.currents.items():
                if cname == "L":
                    self._set_node_state(
                        bneuron,
                        f"g{cname}",
                        node,
                        g * uS / (node.fake_surface * cm2),
                        use_units=True,
                    )
                    self._set_node_state(
                        bneuron, f"e{cname}", node, e * mV, use_units=True
                    )
                else:
                    self._set_node_state(
                        bneuron,
                        f"gbar_{cname}",
                        node,
                        g * uS / (node.fake_surface * cm2),
                        use_units=True,
                    )
                    self._set_node_state(
                        bneuron, f"e_{cname}", node, e * mV, use_units=True
                    )

            if len(conc_ions) > 0:
                self._set_node_state(
                    bneuron, "A_comp", node, node.fake_surface * cm2, use_units=True
                )
                for ion in conc_ions:
                    concmech = node.concmechs.get(ion)
                    if concmech is None:
                        gamma = 0.0
                        tau = 1.0
                        inf = self._initial_concentration(node, ion)
                    else:
                        gamma = concmech.gamma
                        tau = concmech.tau
                        inf = concmech.inf

                    self._set_node_state(
                        bneuron, f"gamma_{ion}", node, gamma, use_units=False
                    )
                    self._set_node_state(
                        bneuron, f"tau_{ion}", node, tau * ms, use_units=True
                    )
                    self._set_node_state(
                        bneuron, f"inf_{ion}", node, inf, use_units=False
                    )

    def add_double_exp_synapse(
        self,
        syn_name: str,
        tau_rise_ms: float,
        tau_decay_ms: float,
        e_rev_mV: float,
    ) -> None:
        """
        Register a double-exponential synapse type to be included in the
        SpatialNeuron equations.

        The synaptic conductance waveform following a presynaptic spike is:

            g(t) = gbar * (exp(-t/tau_decay) - exp(-t/tau_rise)) / norm

        where norm = (tau_decay/tau_rise)^(tau_rise/(tau_decay-tau_rise)) * ...
        is the peak normalisation factor so that g peaks at gbar.

        This is implemented as two state variables per synapse:

            ds_rise_{name}/dt  = -s_rise_{name}  / (tau_rise_{name}  * ms)  : 1 (summed)
            ds_decay_{name}/dt = -s_decay_{name} / (tau_decay_{name} * ms)  : 1 (summed)

        A presynaptic spike delivers:
            s_rise_{name}  += norm_{name}
            s_decay_{name} += norm_{name}

        The conductance is then:
            g_syn_{name} = gbar_{name} * (s_decay_{name} - s_rise_{name})

        and it contributes to Im as:
            gbar_{name} * (s_decay_{name} - s_rise_{name}) * (v - e_{name})

        Parameters
        ----------
        syn_name : str
            Unique identifier for this synapse type, e.g. 'AMPA' or 'GABA_A'.
        tau_rise_ms : float
            Rise time constant [ms].
        tau_decay_ms : float
            Decay time constant [ms].  Must be > tau_rise_ms.
        e_rev_mV : float
            Synaptic reversal potential [mV].
        """
        if tau_decay_ms <= tau_rise_ms:
            raise ValueError(
                f"tau_decay ({tau_decay_ms} ms) must be greater than "
                f"tau_rise ({tau_rise_ms} ms) for synapse '{syn_name}'."
            )
        if not hasattr(self, '_synapses'):
            self._synapses: Dict[str, dict] = {}
        if syn_name in self._synapses:
            raise ValueError(f"Synapse '{syn_name}' already registered.")

        # Peak normalisation factor
        t_peak = (
            np.log(tau_decay_ms / tau_rise_ms)
            / (1.0 / tau_rise_ms - 1.0 / tau_decay_ms)
        )
        norm = 1. / (np.exp(-t_peak / tau_decay_ms) - np.exp(-t_peak / tau_rise_ms))

        self._synapses[syn_name] = {
            'tau_rise_ms':  tau_rise_ms,
            'tau_decay_ms': tau_decay_ms,
            'e_rev_mV':     e_rev_mV,
            'norm':         norm,         # stored for use in Synapses on_pre
        }

    def _synapse_equations(self) -> Tuple[List[str], List[str]]:
        """
        Generate Brian2 equation fragments for all registered synapse types.

        Returns
        -------
        ode_lines : list[str]
            One pair of ODE lines per synapse (rise and decay variables).
        param_decls : list[str]
            Parameter declaration lines (gbar and e_rev per synapse).
        """
        if not hasattr(self, '_synapses') or not self._synapses:
            return [], []

        ode_lines   = []
        param_decls = []

        for syn_name, syn in self._synapses.items():
            tau_r = syn['tau_rise_ms']
            tau_d = syn['tau_decay_ms'] 
            e_rev = syn['e_rev_mV'] * 1e-3   # mV -> V, baked into declaration

            # State variables: (summed) so multiple Synapses objects targeting
            # the same compartment accumulate correctly
            ode_lines += [
                f'ds_rise_{syn_name}/dt  = -s_rise_{syn_name} / ({tau_r} * ms) : siemens ',
                f'ds_decay_{syn_name}/dt = -s_decay_{syn_name}  / ({tau_d} * ms) : siemens  ',
            ]

            # Point current: inward-positive convention (e - v)
            ode_lines.append(
                f'I_syn_{syn_name} = (s_decay_{syn_name} - s_rise_{syn_name}) * (e_{syn_name} - v) : amp (point current)'
            )

            # gbar varies per compartment (different synaptic weight densities);
            # e_rev is fixed per synapse type so we bake it in as a constant
            param_decls += [
                f'e_{syn_name}    : volt (shared)',
            ]

        return ode_lines, param_decls


    def get_on_pre(self, syn_name: str) -> str:
        """
        Return the Brian2 Synapses on_pre string for a registered synapse.

        The increment is normalised so that the conductance peaks at exactly
        gbar regardless of the rise/decay time constants.

        Parameters
        ----------
        syn_name : str
            Name of a synapse previously registered via add_double_exp_synapse().
        weight : float
            Synaptic weight (peak conductance in nS) to scale the on_pre increment.

        Returns
        -------
        str
            on_pre string to pass to brian2.Synapses, e.g.
            's_rise_AMPA_post += 0.9987 * w_var; s_decay_AMPA_post += 0.9987 * w_var'
        """
        syn  = self._synapses[syn_name]
        norm = syn['norm']
        return (
            f's_rise_{syn_name}_post  += {norm:.10f} * w_var; '
            f's_decay_{syn_name}_post += {norm:.10f} * w_var'
        )

    def initialise_at_veq(self, bneuron):
        conc_ions = self._concentration_ions()
        for node in self:
            self._set_node_state(bneuron, "v", node, node.e_eq * mV, use_units=True)

            for ion in conc_ions:
                self._set_node_state(
                    bneuron,
                    f"c_{ion}",
                    node,
                    self._initial_concentration(node, ion),
                    use_units=False,
                )

            for cname, channel in self._channel_storage.items():
                conc_kwargs = {
                    str(c_sym): self._initial_concentration(node, str(c_sym))
                    for c_sym in channel.conc
                }
                args = channel._args_as_list(node.e_eq, w_statevar=False, **conc_kwargs)
                for svar in channel.ordered_statevars:
                    val = float(np.asarray(channel.f_varinf[svar](*args)))
                    self._set_node_state(
                        bneuron, f"{str(svar)}_{cname}", node, val, use_units=False
                    )

    def init_model(self, threshold='v > -20*mV', refractory='v > -30*mV'):
        """
        Build and return a Brian2 SpatialNeuron with Hines implicit solver.

        Parameters
        ----------
        threshold : str
            Spike threshold condition (evaluated at soma, index 0).
        refractory : Quantity
            Refractory period.

        Returns
        -------
        neuron : brian2.SpatialNeuron
        """
        bmorph = self._build_morphology()
        eqs    = self._build_equations()
        
        neuron = brian2.SpatialNeuron(
            morphology         = bmorph,
            model              = eqs,
            Cm                 = self.fake_c_m * uF / cm2,
            Ri                 = self.fake_r_a * Mohm * cm,  # ohm*m -> ohm*cm
            threshold          = threshold,
            threshold_location = 0,
            refractory         = refractory,
            method ='exponential_euler',
        )

        self._set_parameters(neuron)
        self.initialise_at_veq(neuron)

        return neuron
