name: NEAT build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_neat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.10', '3.12' ]
        
      fail-fast: false

    steps:
      # Checkout the repository contents
      - name: Checkout NEAT code
        uses: actions/checkout@v4

      # Setup Python version
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install NEAT (repeated)
      - name: Install NEAT
        run: |
          pip install .

      # Unit tests
      - name: Run tests
        run: |
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests