name: NEAT build

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_nest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nest_branch: ["v3.8", "master"]
      fail-fast: false

    steps:
      # Checkout the repository contents
      - name: Checkout NEAT code
        uses: actions/checkout@v4

      # Setup Python version
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      # Install dependencies
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libltdl7-dev libgsl0-dev libncurses5-dev libreadline6-dev pkg-config
          sudo apt-get install python3-all-dev python3-matplotlib python3-numpy python3-scipy ipython3

      # Install Python dependencies
      - name: Python dependencies
        run: |
          python -m pip install -r requirements.txt

      # Install NEAT (repeated)
      - name: Install NEAT
        run: |
          export PYTHONPATH=${{ env.PYTHONPATH }}:${{ env.NEST_INSTALL }}/lib/python3.10/site-packages
          #echo PYTHONPATH=`pwd` >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          python setup.py install

      - name: Compile channels
        run: |
          neatmodels install default -s neuron

      # Unit tests
      - name: Run unit tests
        run: |
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_cnet.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_compartmentfitter.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_compartmenttee.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_concmechs.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_greenstree.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_ionchannels.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_morphtree.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_net.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_neurontree.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_phystree.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_sovtree.py
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests/test_stree.py