name: NEAT build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_neat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nest_branch: ["v3.8", "master"]
      fail-fast: false

    steps:
      # Checkout the repository contents
      - name: Checkout NEAT code
        uses: actions/checkout@v4

      # Setup Python version
      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      # # Install dependencies
      # - name: Install apt dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install libltdl7-dev libgsl0-dev libncurses5-dev libreadline6-dev pkg-config
      #     sudo apt-get install python3-all-dev python3-matplotlib python3-numpy python3-scipy ipython3

      # # Install Python dependencies
      # - name: Python dependencies
      #   run: |
      #     python -m pip install -r requirements/requirements.txt

      # Install NEAT (repeated)
      - name: Install NEAT
        run: |
          # export PYTHONPATH=${{ env.PYTHONPATH }}:${{ env.NEST_INSTALL }}/lib/python3.8/site-packages
          # #echo PYTHONPATH=`pwd` >> $GITHUB_ENV
          # echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
          pip install .

      # Unit tests
      - name: Run tests
        run: |
          pytest -s -o norecursedirs='*' -o log_cli=true -o log_cli_level="DEBUG" tests