name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nest-neat
    permissions:
      id-token: write # Required for OIDC authentication with PyPI
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for versioning if needed
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip' # Cache pip dependencies for faster builds
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools # 'build' is the modern standard
      - name: Build package distributions
        run: |
          python -m build --sdist --wheel # Modern way to build sdist and wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1